###
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Сергей",
  "login": "LordOfTheHouse",
  "password": "password",
  "email": "LordOfTheHouse@gmail.com"
}

###
GET localhost:8080/users/1
Content-Type: application/json

###
DELETE localhost:8080/users/100

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Кофе",
  "price": 500
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 4,
  "name": "Капуста",
  "price": 75
}

###
DELETE localhost:8080/products/6

###
GET localhost:8080/products/2

###
GET localhost:8080/products?name=Кофе
Content-Type: application/json

###
GET localhost:8080/products
Content-Type: application/json

###
POST localhost:8080/cart/2/product/10
Content-Type: application/json

{
  "amount": 1
}

###
POST localhost:8080/cart/2/product/4
Content-Type: application/json

{
  "amount": 1
}

###
PUT localhost:8080/cart/2/product/4
Content-Type: application/json

{
  "amount": 3
}

###
DELETE localhost:8080/cart/2/product/4

###
GET localhost:8080/users/1
Content-Type: application/json

###
POST localhost:8080/payment
Content-Type: application/json

{
  "cardNumber": 123444,
  "userId": 1
}

