###
POST localhost:8080/users
Content-Type: application/json

{
  "name": "Рандом",
  "login": "random",
  "password": "11111",
  "email": "random@gmail.com"
}

###
GET localhost:8080/users/4
Content-Type: application/json

###
DELETE localhost:8080/users/4

###
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Лайм",
  "price": 80,
  "amount": 10
}

###
PUT localhost:8080/products
Content-Type: application/json

{
  "id": 4,
  "name": "Капуста",
  "price": 90
}

###
DELETE localhost:8080/products/4

###
GET localhost:8080/products/3

###
GET localhost:8080/products?name=Кофе
Content-Type: application/json

###
GET localhost:8080/products
Content-Type: application/json

###
POST localhost:8080/cart/2/product/2
Content-Type: application/json

{
  "amount": 3
}

###
POST localhost:8080/cart/2/product/3
Content-Type: application/json

{
  "amount": 1
}

###
PUT localhost:8080/cart/2/product/2
Content-Type: application/json

{
  "amount": 10
}

###
DELETE localhost:8080/cart/2/product/2

###
GET localhost:8080/users/2
Content-Type: application/json

###
POST localhost:8080/payment
Content-Type: application/json

{
  "cardNumber": 143456,
  "userId": 2
}

